module WineStore; end
require "winestore/version"
require "winestore/customer"
require "winestore/bill"
require "winestore/bill_formatter"
require "winestore/collection_wrapper"
require "winestore/payment"
require "winestore/payments"
require "winestore/purchases"
require "winestore/purchase"
require "winestore/wine_price_code"
require "winestore/wine_price_codes"
require "winestore/wine"